pipeline {
  agent any

  stages {

    stage('Terraform INIT') {
      steps {
        sh 'cd terraform ; terraform init'
      }
    }

    stage('Terraform Destroy') {
      steps {
        sh '''
          cd terraform
          terraform destroy -auto-approve
        '''
      }
    }

  }
}
