frontend:	Install frontend component
    @echo frontend.sh
catalogue:   Install catalogue component
    @echo catalogue.sh
cart:    Install cart component
    @echo cart.sh
user:    Install user component
    @echo user.sh
shipping:    Install shipping component
    @echo shipping.sh
payment:   Install payment component
    @echo payment.sh
mongodb:   Install mongodb component
    @echo mongodb.sh
redis:   Install redis component
    @echo redis.sh
mysql:   Install mysql component
    @echo mysql.sh
rabbitmq:    Install rabbitmq component
    @echo rabbitmq.sh

